import React from "react";

const FullRecipie = ({ recipieID, recipieImage, recipieTitle }) => {
  //GET https://api.spoonacular.com/recipes/{{RECIPIE_ID}}/information?apiKey=${API_KEY}&includeNutrition=true
  const recipieInfo = {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 6,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 0,
    spoonacularScore: 56.0,
    healthScore: 19.0,
    creditsText: "Jen West",
    sourceName: "Pink When",
    pricePerServing: 440.93,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "solid",
        name: "apple",
        nameClean: "apple",
        original: "apple slicer (*optional)",
        originalString: "apple slicer (*optional)",
        originalName: "apple slicer (*optional)",
        amount: 1.0,
        unit: "serving",
        meta: ["(*optional)"],
        metaInformation: ["(*optional)"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 6008,
        aisle: "Canned and Jarred",
        image: "beef-broth.png",
        consistency: "liquid",
        name: "beef broth",
        nameClean: "beef broth",
        original: "2 cups beef broth",
        originalString: "2 cups beef broth",
        originalName: "beef broth",
        amount: 2.0,
        unit: "cups",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10219335,
        aisle: "Spices and Seasonings",
        image: "cinnamon-sugar.png",
        consistency: "solid",
        name: "cinnamon sugar",
        nameClean: "cinnamon sugar",
        original: "cinnamon sugar (*optional)",
        originalString: "cinnamon sugar (*optional)",
        originalName: "cinnamon sugar (*optional)",
        amount: 1.0,
        unit: "serving",
        meta: ["(*optional)"],
        metaInformation: ["(*optional)"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 1069003,
        aisle: "Produce",
        image: "grannysmith-apple.png",
        consistency: "solid",
        name: "green apples",
        nameClean: "green apple",
        original: "2 green apples",
        originalString: "2 green apples",
        originalName: "green apples",
        amount: 2.0,
        unit: "",
        meta: ["green"],
        metaInformation: ["green"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10218,
        aisle: "Meat",
        image: "pork-tenderloin-raw.png",
        consistency: "solid",
        name: "pork tenderloin",
        nameClean: "pork tenderloin",
        original: "Pork Tenderloin",
        originalString: "Pork Tenderloin",
        originalName: "Pork Tenderloin",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
    ],
    id: 673463,
    title: "Slow Cooker Apple Pork Tenderloin",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: "http://www.pinkwhen.com/slow-cooker-apple-pork-tenderloin/",
    image: "https://spoonacular.com/recipeImages/673463-556x370.jpg",
    imageType: "jpg",
    nutrition: {
      nutrients: [
        {
          name: "Calories",
          title: "Calories",
          amount: 462.62,
          unit: "kcal",
          percentOfDailyNeeds: 23.13,
        },
        {
          name: "Fat",
          title: "Fat",
          amount: 6.51,
          unit: "g",
          percentOfDailyNeeds: 10.02,
        },
        {
          name: "Saturated Fat",
          title: "Saturated Fat",
          amount: 2.23,
          unit: "g",
          percentOfDailyNeeds: 13.94,
        },
        {
          name: "Carbohydrates",
          title: "Carbohydrates",
          amount: 71.09,
          unit: "g",
          percentOfDailyNeeds: 23.7,
        },
        {
          name: "Net Carbohydrates",
          title: "Net Carbohydrates",
          amount: 60.85,
          unit: "g",
          percentOfDailyNeeds: 22.13,
        },
        {
          name: "Sugar",
          title: "Sugar",
          amount: 56.29,
          unit: "g",
          percentOfDailyNeeds: 62.54,
        },
        {
          name: "Cholesterol",
          title: "Cholesterol",
          amount: 87.1,
          unit: "mg",
          percentOfDailyNeeds: 29.03,
        },
        {
          name: "Sodium",
          title: "Sodium",
          amount: 1859.67,
          unit: "mg",
          percentOfDailyNeeds: 80.86,
        },
        {
          name: "Protein",
          title: "Protein",
          amount: 34.25,
          unit: "g",
          percentOfDailyNeeds: 68.5,
        },
        {
          name: "Vitamin B1",
          title: "Vitamin B1",
          amount: 1.4,
          unit: "mg",
          percentOfDailyNeeds: 93.2,
        },
        {
          name: "Vitamin B3",
          title: "Vitamin B3",
          amount: 12.99,
          unit: "mg",
          percentOfDailyNeeds: 64.95,
        },
        {
          name: "Selenium",
          title: "Selenium",
          amount: 44.03,
          unit: "µg",
          percentOfDailyNeeds: 62.91,
        },
        {
          name: "Vitamin B6",
          title: "Vitamin B6",
          amount: 1.25,
          unit: "mg",
          percentOfDailyNeeds: 62.4,
        },
        {
          name: "Phosphorus",
          title: "Phosphorus",
          amount: 434.94,
          unit: "mg",
          percentOfDailyNeeds: 43.49,
        },
        {
          name: "Fiber",
          title: "Fiber",
          amount: 10.24,
          unit: "g",
          percentOfDailyNeeds: 40.94,
        },
        {
          name: "Vitamin B2",
          title: "Vitamin B2",
          amount: 0.67,
          unit: "mg",
          percentOfDailyNeeds: 39.15,
        },
        {
          name: "Potassium",
          title: "Potassium",
          amount: 1242.42,
          unit: "mg",
          percentOfDailyNeeds: 35.5,
        },
        {
          name: "Vitamin C",
          title: "Vitamin C",
          amount: 19.62,
          unit: "mg",
          percentOfDailyNeeds: 23.78,
        },
        {
          name: "Zinc",
          title: "Zinc",
          amount: 2.68,
          unit: "mg",
          percentOfDailyNeeds: 17.85,
        },
        {
          name: "Vitamin B12",
          title: "Vitamin B12",
          amount: 1.03,
          unit: "µg",
          percentOfDailyNeeds: 17.21,
        },
        {
          name: "Magnesium",
          title: "Magnesium",
          amount: 67.11,
          unit: "mg",
          percentOfDailyNeeds: 16.78,
        },
        {
          name: "Vitamin B5",
          title: "Vitamin B5",
          amount: 1.48,
          unit: "mg",
          percentOfDailyNeeds: 14.78,
        },
        {
          name: "Iron",
          title: "Iron",
          amount: 2.63,
          unit: "mg",
          percentOfDailyNeeds: 14.63,
        },
        {
          name: "Copper",
          title: "Copper",
          amount: 0.24,
          unit: "mg",
          percentOfDailyNeeds: 11.76,
        },
        {
          name: "Manganese",
          title: "Manganese",
          amount: 0.22,
          unit: "mg",
          percentOfDailyNeeds: 10.83,
        },
        {
          name: "Vitamin K",
          title: "Vitamin K",
          amount: 9.38,
          unit: "µg",
          percentOfDailyNeeds: 8.94,
        },
        {
          name: "Vitamin E",
          title: "Vitamin E",
          amount: 1.06,
          unit: "mg",
          percentOfDailyNeeds: 7.08,
        },
        {
          name: "Calcium",
          title: "Calcium",
          amount: 62.55,
          unit: "mg",
          percentOfDailyNeeds: 6.25,
        },
        {
          name: "Folate",
          title: "Folate",
          amount: 22.4,
          unit: "µg",
          percentOfDailyNeeds: 5.6,
        },
        {
          name: "Vitamin A",
          title: "Vitamin A",
          amount: 232.99,
          unit: "IU",
          percentOfDailyNeeds: 4.66,
        },
        {
          name: "Vitamin D",
          title: "Vitamin D",
          amount: 0.4,
          unit: "µg",
          percentOfDailyNeeds: 2.68,
        },
      ],
      properties: [
        {
          name: "Glycemic Index",
          title: "Glycemic Index",
          amount: 134.09,
          unit: "",
        },
        {
          name: "Glycemic Load",
          title: "Glycemic Load",
          amount: 23.98,
          unit: "",
        },
      ],
      flavonoids: [
        {
          name: "Cyanidin",
          title: "Cyanidin",
          amount: 6.7,
          unit: "mg",
        },
        {
          name: "Petunidin",
          title: "Petunidin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Delphinidin",
          title: "Delphinidin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Malvidin",
          title: "Malvidin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Pelargonidin",
          title: "Pelargonidin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Peonidin",
          title: "Peonidin",
          amount: 0.09,
          unit: "mg",
        },
        {
          name: "Catechin",
          title: "Catechin",
          amount: 5.54,
          unit: "mg",
        },
        {
          name: "Epigallocatechin",
          title: "Epigallocatechin",
          amount: 1.11,
          unit: "mg",
        },
        {
          name: "Epicatechin",
          title: "Epicatechin",
          amount: 32.12,
          unit: "mg",
        },
        {
          name: "Epicatechin 3-gallate",
          title: "Epicatechin 3-gallate",
          amount: 0.04,
          unit: "mg",
        },
        {
          name: "Epigallocatechin 3-gallate",
          title: "Epigallocatechin 3-gallate",
          amount: 0.81,
          unit: "mg",
        },
        {
          name: "Theaflavin",
          title: "Theaflavin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Thearubigins",
          title: "Thearubigins",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Eriodictyol",
          title: "Eriodictyol",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Hesperetin",
          title: "Hesperetin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Naringenin",
          title: "Naringenin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Apigenin",
          title: "Apigenin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Luteolin",
          title: "Luteolin",
          amount: 0.51,
          unit: "mg",
        },
        {
          name: "Isorhamnetin",
          title: "Isorhamnetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Kaempferol",
          title: "Kaempferol",
          amount: 0.6,
          unit: "mg",
        },
        {
          name: "Myricetin",
          title: "Myricetin",
          amount: 0.0,
          unit: "mg",
        },
        {
          name: "Quercetin",
          title: "Quercetin",
          amount: 17.1,
          unit: "mg",
        },
        {
          name: "Theaflavin-3,3'-digallate",
          title: "Theaflavin-3,3'-digallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3'-gallate",
          title: "Theaflavin-3'-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3-gallate",
          title: "Theaflavin-3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Gallocatechin",
          title: "Gallocatechin",
          amount: 0.0,
          unit: "mg",
        },
      ],
      ingredients: [
        {
          id: 9003,
          name: "apple",
          amount: 1.0,
          unit: "serving",
          nutrients: [
            {
              title: "Vitamin B12",
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Iron",
              name: "Iron",
              amount: 0.08,
              unit: "mg",
            },
            {
              title: "Zinc",
              name: "Zinc",
              amount: 0.03,
              unit: "mg",
            },
            {
              title: "Vitamin B3",
              name: "Vitamin B3",
              amount: 0.06,
              unit: "mg",
            },
            {
              title: "Folate",
              name: "Folate",
              amount: 1.88,
              unit: "µg",
            },
            {
              title: "Vitamin C",
              name: "Vitamin C",
              amount: 2.88,
              unit: "mg",
            },
            {
              title: "Fat",
              name: "Fat",
              amount: 0.11,
              unit: "g",
            },
            {
              title: "Vitamin D",
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Fluoride",
              name: "Fluoride",
              amount: 2.06,
              unit: "mg",
            },
            {
              title: "Vitamin B6",
              name: "Vitamin B6",
              amount: 0.03,
              unit: "mg",
            },
            {
              title: "Vitamin B2",
              name: "Vitamin B2",
              amount: 0.02,
              unit: "mg",
            },
            {
              title: "Saturated Fat",
              name: "Saturated Fat",
              amount: 0.02,
              unit: "g",
            },
            {
              title: "Vitamin B1",
              name: "Vitamin B1",
              amount: 0.01,
              unit: "mg",
            },
            {
              title: "Cholesterol",
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Potassium",
              name: "Potassium",
              amount: 66.88,
              unit: "mg",
            },
            {
              title: "Copper",
              name: "Copper",
              amount: 0.02,
              unit: "mg",
            },
            {
              title: "Sugar",
              name: "Sugar",
              amount: 6.49,
              unit: "g",
            },
            {
              title: "Fiber",
              name: "Fiber",
              amount: 1.5,
              unit: "g",
            },
            {
              title: "Phosphorus",
              name: "Phosphorus",
              amount: 6.88,
              unit: "mg",
            },
            {
              title: "Selenium",
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin K",
              name: "Vitamin K",
              amount: 1.38,
              unit: "µg",
            },
            {
              title: "Vitamin A",
              name: "Vitamin A",
              amount: 33.75,
              unit: "IU",
            },
            {
              title: "Vitamin E",
              name: "Vitamin E",
              amount: 0.11,
              unit: "mg",
            },
            {
              title: "Mono Unsaturated Fat",
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Protein",
              name: "Protein",
              amount: 0.16,
              unit: "g",
            },
            {
              title: "Poly Unsaturated Fat",
              name: "Poly Unsaturated Fat",
              amount: 0.03,
              unit: "g",
            },
            {
              title: "Calcium",
              name: "Calcium",
              amount: 3.75,
              unit: "mg",
            },
            {
              title: "Sodium",
              name: "Sodium",
              amount: 0.63,
              unit: "mg",
            },
            {
              title: "Net Carbohydrates",
              name: "Net Carbohydrates",
              amount: 7.13,
              unit: "g",
            },
            {
              title: "Carbohydrates",
              name: "Carbohydrates",
              amount: 8.63,
              unit: "g",
            },
            {
              title: "Folic Acid",
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Alcohol",
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Calories",
              name: "Calories",
              amount: 32.5,
              unit: "kcal",
            },
            {
              title: "Magnesium",
              name: "Magnesium",
              amount: 3.13,
              unit: "mg",
            },
            {
              title: "Caffeine",
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B5",
              name: "Vitamin B5",
              amount: 0.04,
              unit: "mg",
            },
            {
              title: "Choline",
              name: "Choline",
              amount: 2.13,
              unit: "mg",
            },
            {
              title: "Manganese",
              name: "Manganese",
              amount: 0.02,
              unit: "mg",
            },
          ],
        },
        {
          id: 6008,
          name: "beef broth",
          amount: 2.0,
          unit: "cups",
          nutrients: [
            {
              title: "Vitamin B12",
              name: "Vitamin B12",
              amount: 0.34,
              unit: "µg",
            },
            {
              title: "Iron",
              name: "Iron",
              amount: 0.82,
              unit: "mg",
            },
            {
              title: "Zinc",
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B3",
              name: "Vitamin B3",
              amount: 3.74,
              unit: "mg",
            },
            {
              title: "Folate",
              name: "Folate",
              amount: 9.6,
              unit: "µg",
            },
            {
              title: "Vitamin C",
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Fat",
              name: "Fat",
              amount: 1.06,
              unit: "g",
            },
            {
              title: "Vitamin D",
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Fluoride",
              name: "Fluoride",
              amount: 139.2,
              unit: "mg",
            },
            {
              title: "Vitamin B6",
              name: "Vitamin B6",
              amount: 0.05,
              unit: "mg",
            },
            {
              title: "Vitamin B2",
              name: "Vitamin B2",
              amount: 0.1,
              unit: "mg",
            },
            {
              title: "Saturated Fat",
              name: "Saturated Fat",
              amount: 0.53,
              unit: "g",
            },
            {
              title: "Vitamin B1",
              name: "Vitamin B1",
              amount: 0.01,
              unit: "mg",
            },
            {
              title: "Cholesterol",
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Potassium",
              name: "Potassium",
              amount: 259.2,
              unit: "mg",
            },
            {
              title: "Copper",
              name: "Copper",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Sugar",
              name: "Sugar",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Fiber",
              name: "Fiber",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Phosphorus",
              name: "Phosphorus",
              amount: 62.4,
              unit: "mg",
            },
            {
              title: "Selenium",
              name: "Selenium",
              amount: 3.36,
              unit: "µg",
            },
            {
              title: "Vitamin K",
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin A",
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
            },
            {
              title: "Vitamin E",
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Mono Unsaturated Fat",
              name: "Mono Unsaturated Fat",
              amount: 0.43,
              unit: "g",
            },
            {
              title: "Protein",
              name: "Protein",
              amount: 5.47,
              unit: "g",
            },
            {
              title: "Poly Unsaturated Fat",
              name: "Poly Unsaturated Fat",
              amount: 0.05,
              unit: "g",
            },
            {
              title: "Calcium",
              name: "Calcium",
              amount: 28.8,
              unit: "mg",
            },
            {
              title: "Sodium",
              name: "Sodium",
              amount: 1785.6,
              unit: "mg",
            },
            {
              title: "Net Carbohydrates",
              name: "Net Carbohydrates",
              amount: 0.19,
              unit: "g",
            },
            {
              title: "Carbohydrates",
              name: "Carbohydrates",
              amount: 0.19,
              unit: "g",
            },
            {
              title: "Folic Acid",
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Alcohol",
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Calories",
              name: "Calories",
              amount: 33.6,
              unit: "kcal",
            },
            {
              title: "Magnesium",
              name: "Magnesium",
              amount: 9.6,
              unit: "mg",
            },
            {
              title: "Caffeine",
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B5",
              name: "Vitamin B5",
              amount: 0.1,
              unit: "mg",
            },
            {
              title: "Choline",
              name: "Choline",
              amount: 13.92,
              unit: "mg",
            },
            {
              title: "Manganese",
              name: "Manganese",
              amount: 0.05,
              unit: "mg",
            },
          ],
        },
        {
          id: 10219335,
          name: "cinnamon sugar",
          amount: 1.0,
          unit: "serving",
          nutrients: [
            {
              title: "Vitamin B12",
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Iron",
              name: "Iron",
              amount: 0.01,
              unit: "mg",
            },
            {
              title: "Zinc",
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B3",
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Folate",
              name: "Folate",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin C",
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Fat",
              name: "Fat",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Vitamin D",
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Fluoride",
              name: "Fluoride",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B6",
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B2",
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Saturated Fat",
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Vitamin B1",
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Cholesterol",
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Potassium",
              name: "Potassium",
              amount: 0.24,
              unit: "mg",
            },
            {
              title: "Copper",
              name: "Copper",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Sugar",
              name: "Sugar",
              amount: 11.98,
              unit: "g",
            },
            {
              title: "Fiber",
              name: "Fiber",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Phosphorus",
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Selenium",
              name: "Selenium",
              amount: 0.07,
              unit: "µg",
            },
            {
              title: "Vitamin K",
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin A",
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
            },
            {
              title: "Vitamin E",
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Mono Unsaturated Fat",
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Protein",
              name: "Protein",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Poly Unsaturated Fat",
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Calcium",
              name: "Calcium",
              amount: 0.12,
              unit: "mg",
            },
            {
              title: "Sodium",
              name: "Sodium",
              amount: 0.12,
              unit: "mg",
            },
            {
              title: "Net Carbohydrates",
              name: "Net Carbohydrates",
              amount: 12.0,
              unit: "g",
            },
            {
              title: "Carbohydrates",
              name: "Carbohydrates",
              amount: 12.0,
              unit: "g",
            },
            {
              title: "Folic Acid",
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Alcohol",
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Calories",
              name: "Calories",
              amount: 46.44,
              unit: "kcal",
            },
            {
              title: "Magnesium",
              name: "Magnesium",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Caffeine",
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B5",
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Choline",
              name: "Choline",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Manganese",
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
            },
          ],
        },
        {
          id: 1069003,
          name: "green apples",
          amount: 2.0,
          unit: "",
          nutrients: [
            {
              title: "Vitamin B12",
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Iron",
              name: "Iron",
              amount: 0.44,
              unit: "mg",
            },
            {
              title: "Zinc",
              name: "Zinc",
              amount: 0.15,
              unit: "mg",
            },
            {
              title: "Vitamin B3",
              name: "Vitamin B3",
              amount: 0.33,
              unit: "mg",
            },
            {
              title: "Folate",
              name: "Folate",
              amount: 10.92,
              unit: "µg",
            },
            {
              title: "Vitamin C",
              name: "Vitamin C",
              amount: 16.74,
              unit: "mg",
            },
            {
              title: "Fat",
              name: "Fat",
              amount: 0.62,
              unit: "g",
            },
            {
              title: "Vitamin D",
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Fluoride",
              name: "Fluoride",
              amount: 12.01,
              unit: "mg",
            },
            {
              title: "Vitamin B6",
              name: "Vitamin B6",
              amount: 0.15,
              unit: "mg",
            },
            {
              title: "Vitamin B2",
              name: "Vitamin B2",
              amount: 0.09,
              unit: "mg",
            },
            {
              title: "Saturated Fat",
              name: "Saturated Fat",
              amount: 0.1,
              unit: "g",
            },
            {
              title: "Vitamin B1",
              name: "Vitamin B1",
              amount: 0.06,
              unit: "mg",
            },
            {
              title: "Cholesterol",
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Potassium",
              name: "Potassium",
              amount: 389.48,
              unit: "mg",
            },
            {
              title: "Copper",
              name: "Copper",
              amount: 0.1,
              unit: "mg",
            },
            {
              title: "Sugar",
              name: "Sugar",
              amount: 37.82,
              unit: "g",
            },
            {
              title: "Fiber",
              name: "Fiber",
              amount: 8.74,
              unit: "g",
            },
            {
              title: "Phosphorus",
              name: "Phosphorus",
              amount: 40.04,
              unit: "mg",
            },
            {
              title: "Selenium",
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin K",
              name: "Vitamin K",
              amount: 8.01,
              unit: "µg",
            },
            {
              title: "Vitamin A",
              name: "Vitamin A",
              amount: 196.56,
              unit: "IU",
            },
            {
              title: "Vitamin E",
              name: "Vitamin E",
              amount: 0.66,
              unit: "mg",
            },
            {
              title: "Mono Unsaturated Fat",
              name: "Mono Unsaturated Fat",
              amount: 0.03,
              unit: "g",
            },
            {
              title: "Protein",
              name: "Protein",
              amount: 0.95,
              unit: "g",
            },
            {
              title: "Poly Unsaturated Fat",
              name: "Poly Unsaturated Fat",
              amount: 0.19,
              unit: "g",
            },
            {
              title: "Calcium",
              name: "Calcium",
              amount: 21.84,
              unit: "mg",
            },
            {
              title: "Sodium",
              name: "Sodium",
              amount: 3.64,
              unit: "mg",
            },
            {
              title: "Net Carbohydrates",
              name: "Net Carbohydrates",
              amount: 41.53,
              unit: "g",
            },
            {
              title: "Carbohydrates",
              name: "Carbohydrates",
              amount: 50.27,
              unit: "g",
            },
            {
              title: "Folic Acid",
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Alcohol",
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Calories",
              name: "Calories",
              amount: 189.28,
              unit: "kcal",
            },
            {
              title: "Magnesium",
              name: "Magnesium",
              amount: 18.2,
              unit: "mg",
            },
            {
              title: "Caffeine",
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B5",
              name: "Vitamin B5",
              amount: 0.22,
              unit: "mg",
            },
            {
              title: "Choline",
              name: "Choline",
              amount: 12.38,
              unit: "mg",
            },
            {
              title: "Manganese",
              name: "Manganese",
              amount: 0.13,
              unit: "mg",
            },
          ],
        },
        {
          id: 10218,
          name: "pork tenderloin",
          amount: 1.0,
          unit: "serving",
          nutrients: [
            {
              title: "Vitamin B12",
              name: "Vitamin B12",
              amount: 0.7,
              unit: "µg",
            },
            {
              title: "Iron",
              name: "Iron",
              amount: 1.3,
              unit: "mg",
            },
            {
              title: "Zinc",
              name: "Zinc",
              amount: 2.51,
              unit: "mg",
            },
            {
              title: "Vitamin B3",
              name: "Vitamin B3",
              amount: 8.86,
              unit: "mg",
            },
            {
              title: "Folate",
              name: "Folate",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin C",
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Fat",
              name: "Fat",
              amount: 4.73,
              unit: "g",
            },
            {
              title: "Vitamin D",
              name: "Vitamin D",
              amount: 0.4,
              unit: "µg",
            },
            {
              title: "Vitamin B6",
              name: "Vitamin B6",
              amount: 1.03,
              unit: "mg",
            },
            {
              title: "Vitamin B2",
              name: "Vitamin B2",
              amount: 0.45,
              unit: "mg",
            },
            {
              title: "Saturated Fat",
              name: "Saturated Fat",
              amount: 1.58,
              unit: "g",
            },
            {
              title: "Vitamin B1",
              name: "Vitamin B1",
              amount: 1.32,
              unit: "mg",
            },
            {
              title: "Cholesterol",
              name: "Cholesterol",
              amount: 87.1,
              unit: "mg",
            },
            {
              title: "Potassium",
              name: "Potassium",
              amount: 526.62,
              unit: "mg",
            },
            {
              title: "Copper",
              name: "Copper",
              amount: 0.12,
              unit: "mg",
            },
            {
              title: "Sugar",
              name: "Sugar",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Fiber",
              name: "Fiber",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Phosphorus",
              name: "Phosphorus",
              amount: 325.62,
              unit: "mg",
            },
            {
              title: "Selenium",
              name: "Selenium",
              amount: 40.6,
              unit: "µg",
            },
            {
              title: "Vitamin K",
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Vitamin A",
              name: "Vitamin A",
              amount: 2.68,
              unit: "IU",
            },
            {
              title: "Vitamin E",
              name: "Vitamin E",
              amount: 0.29,
              unit: "mg",
            },
            {
              title: "Mono Unsaturated Fat",
              name: "Mono Unsaturated Fat",
              amount: 1.82,
              unit: "g",
            },
            {
              title: "Protein",
              name: "Protein",
              amount: 27.67,
              unit: "g",
            },
            {
              title: "Poly Unsaturated Fat",
              name: "Poly Unsaturated Fat",
              amount: 0.75,
              unit: "g",
            },
            {
              title: "Calcium",
              name: "Calcium",
              amount: 8.04,
              unit: "mg",
            },
            {
              title: "Sodium",
              name: "Sodium",
              amount: 69.68,
              unit: "mg",
            },
            {
              title: "Trans Fat",
              name: "Trans Fat",
              amount: 0.05,
              unit: "g",
            },
            {
              title: "Net Carbohydrates",
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Carbohydrates",
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Folic Acid",
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
            },
            {
              title: "Alcohol",
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
            },
            {
              title: "Calories",
              name: "Calories",
              amount: 160.8,
              unit: "kcal",
            },
            {
              title: "Magnesium",
              name: "Magnesium",
              amount: 36.18,
              unit: "mg",
            },
            {
              title: "Caffeine",
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
            },
            {
              title: "Vitamin B5",
              name: "Vitamin B5",
              amount: 1.12,
              unit: "mg",
            },
            {
              title: "Choline",
              name: "Choline",
              amount: 106.8,
              unit: "mg",
            },
            {
              title: "Manganese",
              name: "Manganese",
              amount: 0.02,
              unit: "mg",
            },
          ],
        },
      ],
      caloricBreakdown: {
        percentProtein: 28.55,
        percentFat: 12.21,
        percentCarbs: 59.24,
      },
      weightPerServing: {
        amount: 1053,
        unit: "g",
      },
    },
    summary:
      'Slow Cooker Apple Pork Tenderloin is a <b>gluten free and primal</b> main course. For <b>$4.19 per serving</b>, this recipe <b>covers 27%</b> of your daily requirements of vitamins and minerals. One serving contains <b>486 calories</b>, <b>34g of protein</b>, and <b>12g of fat</b>. Only a few people made this recipe, and 1 would say it hit the spot. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Head to the store and pick up pork tenderloin, apples, cinnamon sugar, and a few other things to make it today. To use up the apple you could follow this main course with the <a href="https://spoonacular.com/recipes/apple-party-from-the-vault-apple-craisin-bread-pudding-515137">Apple Party! From the Vault – Apple Craisin Bread Pudding</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 58%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/slow-cooker-pork-tenderloin-143861">Slow Cooker Pork Tenderloin</a>, <a href="https://spoonacular.com/recipes/havana-slow-cooker-pork-tenderloin-357547">Havana Slow Cooker Pork Tenderloin</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-teriyaki-pork-tenderloin-470380">Slow Cooker Teriyaki Pork Tenderloin</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    winePairing: {
      pairedWines: ["malbec", "pinot noir", "sangiovese"],
      pairingText:
        "Pork Tenderloin works really well with Malbec, Pinot Noir, and Sangiovese. Pinot noir's light body is great for lean cuts, medium bodied sangiovese complement meaty sauces, stews, and other multi-ingredient dishes, and full-bodied tannic malbec pairs with fatty cuts and barbecue. The Reginato Malbec rosé with a 4.8 out of 5 star rating seems like a good match. It costs about 17 dollars per bottle.",
      productMatches: [
        {
          id: 455075,
          title: "Reginato Malbec Rose",
          description:
            "Malbec seems an unlikely hero for a sparkling wine grape, but when you want your rosé to show some real color and character, then Malbec's your man. Crisp and dry with lovely strawberry, rhubarb flavors and aromas. Just a hint of tannin structure, floral spice, and an amazing elegant finish rounds out the mouth. It speaks of the rich Malbec grape, but never loses its light, refreshing nature. It will give you a good reason to drink sparkling wine with your main course!",
          price: "$16.99",
          imageUrl: "https://spoonacular.com/productImages/455075-312x231.jpg",
          averageRating: 0.96,
          ratingCount: 7.0,
          score: 0.9145454545454546,
          link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Freginato-malbec-rose%2F147678",
        },
      ],
    },
    // instructions: null,
    instructions:
      "Wow what awesome instructions! I totally didn't just hard-code these!<ol><li>Add the stuff</li><li>Do the stuff</li><li>Plate the stuff</li><li>Serve the stuff</li><li>Eat the stuff</li>",
    analyzedInstructions: [],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/slow-cooker-apple-pork-tenderloin-673463",
  };

  return (
    <div id="recipie">
      <img src={recipieImage} id="mainImage" />
      <h2 id="recipieTitle">{recipieTitle}</h2>
      <p id="info">
        Time: {recipieInfo.readyInMinutes} Min. | Makes: {recipieInfo.servings}{" "}
        Servings | Diets: {recipieInfo.diets.join(", ")}
        <br />
        From: <a href={recipieInfo.sourceUrl}>
          {recipieInfo.sourceName}
        </a> by: {recipieInfo.creditsText}
      </p>
      <p
        id="description"
        dangerouslySetInnerHTML={{ __html: recipieInfo.summary }}
      ></p>
      <hr />
      {recipieInfo.instructions ? (
        <p
          id="instructions"
          dangerouslySetInnerHTML={{ __html: recipieInfo.instructions }}
        ></p>
      ) : (
        <p id="instructions">
          The API doesn't have instructions avalible for this recipie, but you
          might find them here:{" "}
          <a href={recipieInfo.sourceUrl}>{recipieInfo.sourceUrl}</a>
        </p>
      )}
    </div>
  );
};

export default FullRecipie;
